### ISSUE TITLE
Problem in code

### ISSUE THREAD

**Issue by Zeyu-Xiao** [Jukgei/gic#1]
![image](https://github.com/user-attachments/assets/c4b20e41-372f-4a1d-832b-1da839ad52f4)
It's a great work, but I am just really curious about why the line 196 use torch.mean instead of torch.sum? In your paper just simply use co*basis and sum them up, is there any thing may mislead me?

**Comment by caijunhao** [comment]
@always-anything Thank you for your interest. 
Since each motion basis is regarded as an individual trajectory, we should use the mean operation to perform linear combination among these bases. If we use the sum op, the whole module might still work, but the basis here is no longer representing the trajectory.

**Comment by Zeyu-Xiao** [comment]
> @always-anything Thank you for your interest. Since each motion basis is regarded as an individual trajectory, we should use the mean operation to perform linear combination among these bases. If we use the sum op, the whole module might still work, but the basis here is no longer representing the trajectory.

Now I could understand it, thanks!
